/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.ort.obligatorio.ui;

import edu.ort.obligatorio.controladores.ControladorVistaAtenderLlamada;
import edu.ort.obligatorio.dominio.Cliente;
import edu.ort.obligatorio.dominio.ClienteGestor;
import edu.ort.obligatorio.dominio.Llamada;
import edu.ort.obligatorio.dominio.Puesto;
import edu.ort.obligatorio.dominio.Sector;
import edu.ort.obligatorio.logica.Fachada;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leand
 */
public class VistaAtenderLlamadaImp extends javax.swing.JDialog implements VistaAtenderLlamada{
    ControladorVistaAtenderLlamada controlador;
    /**
     * Creates new form VistaAtenderLlamada
     */
    public VistaAtenderLlamadaImp(Puesto modelo) {
        initComponents();
        this.controlador = new ControladorVistaAtenderLlamada(this,modelo);
        this.setTitle("Aplicacion para trabajadores");
        inicializar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombreSector = new javax.swing.JLabel();
        lNumeroPuesto = new javax.swing.JLabel();
        txtNombreSector = new javax.swing.JTextField();
        txtNombreTrabajador = new javax.swing.JTextField();
        txtNumeroPuesto = new javax.swing.JTextField();
        lLlamadasAtendidas = new javax.swing.JLabel();
        lTiempoPromedio = new javax.swing.JLabel();
        txtLlamadasAtendidas = new javax.swing.JTextField();
        txtTiempoPromedio = new javax.swing.JTextField();
        txtEstadoLLamada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcionLlamada = new javax.swing.JTextArea();
        lDescripcionLlamada = new javax.swing.JLabel();
        lNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        bFinalizarLlamada = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lNombreSector.setText("Sector:");

        lNumeroPuesto.setText("|   Puesto Nro. #");

        txtNombreSector.setEditable(false);

        txtNombreTrabajador.setEditable(false);

        txtNumeroPuesto.setEditable(false);
        txtNumeroPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroPuestoActionPerformed(evt);
            }
        });

        lLlamadasAtendidas.setText("Llamadas Atendidas:");

        lTiempoPromedio.setText("Tiempo Promedio:");

        txtLlamadasAtendidas.setEditable(false);
        txtLlamadasAtendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlamadasAtendidasActionPerformed(evt);
            }
        });

        txtTiempoPromedio.setEditable(false);

        txtEstadoLLamada.setEditable(false);
        txtEstadoLLamada.setText("Esperando llamada...");
        txtEstadoLLamada.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        txtEstadoLLamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoLLamadaActionPerformed(evt);
            }
        });

        txtaDescripcionLlamada.setColumns(20);
        txtaDescripcionLlamada.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcionLlamada);

        lDescripcionLlamada.setText("Descripcion:");

        lNombreCliente.setText("Cliente:");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        bFinalizarLlamada.setText("Finalizar Llamada");
        bFinalizarLlamada.setEnabled(false);
        bFinalizarLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarLlamadaActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lNombreCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(257, 257, 257)
                            .addComponent(bFinalizarLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEstadoLLamada, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lNombreSector)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNombreSector, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lNumeroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNumeroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lLlamadasAtendidas)
                                        .addComponent(lTiempoPromedio))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLlamadasAtendidas, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(txtTiempoPromedio)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lDescripcionLlamada)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lLlamadasAtendidas)
                            .addComponent(txtLlamadasAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(txtTiempoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNombreSector, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumeroPuesto)
                            .addComponent(txtNombreSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTiempoPromedio))))
                .addGap(61, 61, 61)
                .addComponent(txtEstadoLLamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNombreCliente)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lDescripcionLlamada)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bFinalizarLlamada)
                    .addComponent(bSalir))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPuestoActionPerformed

    private void txtLlamadasAtendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlamadasAtendidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLlamadasAtendidasActionPerformed

    private void txtEstadoLLamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoLLamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoLLamadaActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Cliente c = new Cliente("789","Cliente1",new ClienteGestor(),500f);
        Cliente c2 = new Cliente("4568","Cliente2",new ClienteGestor(),500f);

        Sector sector1 = Fachada.getInstancia().getSector(1);
        Llamada l = new Llamada(c,sector1);
        Llamada l2 = new Llamada(c2,sector1);
        Llamada l3 = new Llamada(c,sector1);
        Llamada l4 = new Llamada(c,sector1);
        Llamada l5 = new Llamada(c,sector1);
        Llamada l6 = new Llamada(c,sector1);



        try {
            Fachada.getInstancia().iniciarLlamada(l);
        } catch (Exception ex) {
            mostrarMensajeDeError(ex.getMessage());
        }
        
        try {
            Fachada.getInstancia().iniciarLlamada(l2);
        } catch (Exception ex) {
            mostrarMensajeDeError(ex.getMessage());
        }
        
        try {
            Fachada.getInstancia().iniciarLlamada(l3);
        } catch (Exception ex) {
            mostrarMensajeDeError(ex.getMessage());
        }
        
        try {
            Fachada.getInstancia().iniciarLlamada(l4);
        } catch (Exception ex) {
            mostrarMensajeDeError(ex.getMessage());
        }
        
        try {
            Fachada.getInstancia().iniciarLlamada(l5);
        } catch (Exception ex) {
            mostrarMensajeDeError(ex.getMessage());
        }
        
        try {
            Fachada.getInstancia().iniciarLlamada(l6);
        } catch (Exception ex) {
            mostrarMensajeDeError(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void bFinalizarLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarLlamadaActionPerformed
        // TODO add your handling code here:
        try {
            String descripcionDeLLamada = txtaDescripcionLlamada.getText();
            controlador.setearDescirpcionDeLlamada(descripcionDeLLamada);
            controlador.finalizarLlamada();
        }
        catch(Exception ex){
            mostrarMensajeDeError(ex.getMessage());
        }
    }//GEN-LAST:event_bFinalizarLlamadaActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFinalizarLlamada;
    private javax.swing.JButton bSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDescripcionLlamada;
    private javax.swing.JLabel lLlamadasAtendidas;
    private javax.swing.JLabel lNombreCliente;
    private javax.swing.JLabel lNombreSector;
    private javax.swing.JLabel lNumeroPuesto;
    private javax.swing.JLabel lTiempoPromedio;
    private javax.swing.JTextField txtEstadoLLamada;
    private javax.swing.JTextField txtLlamadasAtendidas;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreSector;
    private javax.swing.JTextField txtNombreTrabajador;
    private javax.swing.JTextField txtNumeroPuesto;
    private javax.swing.JTextField txtTiempoPromedio;
    private javax.swing.JTextArea txtaDescripcionLlamada;
    // End of variables declaration//GEN-END:variables

    @Override
    public void nombreSector(String nombreSector) {
        txtNombreSector.setText(nombreSector);
    }

    @Override
    public void numeroPuesto(int numeroPuesto) {
        txtNumeroPuesto.setText(String.valueOf(numeroPuesto));
    }

    @Override
    public void cantidadLlamadasAtendidas(int cantidadLlamadas) {
        txtLlamadasAtendidas.setText(String.valueOf(cantidadLlamadas));
    }

    @Override
    public void tiempoPromedioLlamadas(float tiempoPromedio) {
        txtTiempoPromedio.setText(String.valueOf(tiempoPromedio));
    }

    @Override
    public void nombreTrabajador(String nombreTrabajador) {
        txtNombreTrabajador.setText(nombreTrabajador);
    }

    @Override
    public void nombreCliente(String nombreCliente) {
        txtNombreCliente.setText(nombreCliente);
    }
    
    private void inicializar() {
        controlador.inicializar();
    }

    @Override
    public void estadoLlamadaEnCurso() {
        txtEstadoLLamada.setForeground(new Color(50,155,13));
        txtEstadoLLamada.setText("Llamada en Curso...");
        bFinalizarLlamada.setEnabled(true);
    }

    @Override
    public void estadoLlamadaEsperandoLlamada() {
        txtEstadoLLamada.setForeground(new Color(121,13,155));
        txtEstadoLLamada.setText("Esperando Llamada...");
        bFinalizarLlamada.setEnabled(false);
    }
    
    @Override
    public void estadoLlamadaFinalizada() {
        txtEstadoLLamada.setForeground(new Color(158, 16, 72 ));
        txtEstadoLLamada.setText("Llamada Finalizada...");
        bFinalizarLlamada.setEnabled(false);
    }
    
    @Override
    public void mostrarMensajeDeError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    @Override
    public void reset(){
        txtNombreCliente.setText("");
        txtaDescripcionLlamada.setText("");
    }
}
    
    
