/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.ort.obligatorio.ui;

import edu.ort.obligatorio.controladores.ControladorVistaAtenderLlamada;
import edu.ort.obligatorio.dominio.Puesto;
import javax.swing.JFrame;

/**
 *
 * @author leand
 */
public class VistaAtenderLlamada extends javax.swing.JDialog implements VistaAtenderLlamadaInterfaz{
    ControladorVistaAtenderLlamada controlador;
    /**
     * Creates new form VistaAtenderLlamada
     */
    public VistaAtenderLlamada(Puesto modelo) {
        initComponents();
        this.controlador = new ControladorVistaAtenderLlamada(this,modelo);
        this.nombreSector();
        this.nombreTrabajador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    @Override
    public String nombreSector() {
        return controlador.nombreSector();
    }

    @Override
    public int numeroPuesto() {
       return controlador.numeroPuesto();
    }

    @Override
    public int cantidadLlamadasAtendidas() {
        return controlador.cantidadLlamadasAtendidas();
    }

    @Override
    public float tiempoPromedioLlamadas() {
        return controlador.tiempoPromedioLlamadas();
    }

    @Override
    public String nombreTrabajador() {
        return controlador.nombreTrabajador();
    }

    @Override
    public String nombreCliente() {
        return controlador.nombreCliente();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
